### ISSUE TITLE
HTTP 422 error on multiple submits to the same branch

### ISSUE THREAD

**Issue by perseids-proxy-user** [PonteIneptique/flask-github-proxy#14]
in my testing I sent multiple submits to the same branch (which shouldn't happen in production), and in that case I received a 422 instead of a 201, which is a little strange as an error (unprocessable entity) and oddly enough, the commits seem to have worked, and updated the original PR, despite reporting this error. 

Not sure if we care about this or not, since it shouldn't happen in production, but wanted to make a note of it.

**Comment by PonteIneptique** [comment]
You get a 422 because you are trying to open a PR which already exists. This seems totally normal. This comes later in the process

**Comment by PonteIneptique** [comment]
See #16
