### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by PonteIneptique** [PonteIneptique/flask-github-proxy#22]
Hey @balmas ,
Could you deploy the latest version ? I would like to be sure it works (even if all unit tested) before pushing to pypy ;)

**Comment by balmas** [comment]
I will do so tomorrow.

**Comment by PonteIneptique** [comment]
Note that I added a new information in case of error on the api response. The json dictionary contains now the "step" key which tells us where it failed.

**Comment by balmas** [comment]
Deployed, and tested and it seems to be working fine.

**Comment by PonteIneptique** [comment]
Pushing to pypy then

**Comment by PonteIneptique** [comment]
You can now replace your install with a pypy install ;)
